
wrapper:
  mode: offline #offline or realtime
  bag_path: /dataset/m2dgr/street_04_lig.bag
  save_pcd: true
  speed_factor: 12.0
  visualization_mode: pangolin #pangolin or rviz
  config_file_name: m2dgr.yaml
  lidar_topic: /velodyne_points
  imu_topic: /handsfree/imu
  lidar_type: 1 # velodyne
  time_unit: 1e-6
front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  extrin_t: [0,0,0.28]
  use_inv: 1
  trajectory_save: true
  trajectory_save_file: m2dgr.txt
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001
