
wrapper:
  mode: offline #offline or realtime
  bag_path: /dataset/nclt/nclt9.bag
  save_pcd: false
  speed_factor: 20.0
  visualization_mode: rviz #pangolin or rviz
  config_file_name: nclt.yaml
  lidar_topic: points_raw
  imu_topic: imu_raw
  lidar_type: 1 # velodyne
  time_unit: 1e-6
  point_filter_num: 6          
  scan_line: 32
  blind: 4
front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  # extrin_r: [0.9998477, -0.0174524, 0,
  #          0.0174524,  0.9998477, 0,
  #          0,          0,         1]
  extrin_t: [0,0,0.28]
  use_inv: 0
  trajectory_save: true
  trajectory_save_file: nclt9.txt
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001
